version: "2"
services:
  base:
    privileged: true
    cap_add:
      - ALL            
    build: ./base/
    image: ansible_base
  master:
    links:
      - base
    privileged: true
    cap_add:
      - ALL          
    build: ./master/
    image: ansible_master
    container_name: master01
    hostname: master01
    command: ["/usr/sbin/sshd","-D"]
    volumes:
      - ansible_vol:/var/ans
  host:
    links:
      - base
      - master
    privileged: true
    cap_add:
      - ALL
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans
  host02:
    links:
      - base
      - master
      - host
    privileged: true
    cap_add:
      - ALL
    image: ansible_host
    container_name: host02
    hostname: host02
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans
  host03:
    links:
      - base
      - master
      - host
    privileged: true
    cap_add:
      - ALL
    image: ansible_host
    container_name: host03
    hostname: host03
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans
volumes:
  ansible_vol:
